<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $block \Magento\Customer\Block\Address\Book
 */
?>
<div class="block block-addresses-default">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Default Addresses') ?></strong></div>
    <div class="block-content">
        <div class="row">
            <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
                <div class="col-sm-6">
                    <div class="box box-address-billing">
                        <strong class="box-title">
                            <span><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></span>
                            <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Change Billing Address') ?></span>
                            </a>
                        </strong>
                        <div class="box-content">
                            <address>
                                <?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                            </address>
                        </div>
<!--                        <div class="box-actions">-->
<!--                            -->
<!--                        </div>-->
                    </div>
                </div>
            <?php else: ?>
                <div class="col-sm-6">
                    <div class="box box-billing-address">
                        <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></span></strong>
                        <div class="box-content">
                            <p><?php /* @escapeNotVerified */ echo __('You have no default billing address in your address book.') ?></p>
                        </div>
                    </div>
                </div>
            <?php endif ?>

            <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
                <div class="col-sm-6">
                    <div class="box box-address-shipping">
                        <strong class="box-title">
                            <span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span>
                            <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>">
                                <span><?php /* @escapeNotVerified */ echo __('Change Shipping Address') ?></span>
                            </a>
                        </strong>
                        <div class="box-content">
                            <address>
                                <?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                            </address>
                        </div>
<!--                        <div class="box-actions">-->
<!--                            -->
<!--                        </div>-->
                    </div>
                </div>
            <?php else: ?>
                <div class="col-sm-6">
                    <div class="box box-shipping-address">
                        <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span></strong>
                        <div class="box-content">
                            <p><?php /* @escapeNotVerified */ echo __('You have no default shipping address in your address book.') ?></p>
                        </div>
                    </div>
                </div>
            <?php endif ?>

        </div>
    </div>
</div>